# inventory/group_vars/all.yml
---
ansible_user: admin
ansible_ssh_private_key_file: ~/.ssh/id_ed25519

luxnix_dev_repo: "/home/admin/luxnix"
luxnix_repo: "https://github.com/wg-lux/luxnix-refactor.git"
luxnix_dest: "/home/admin/luxnix-test-target"

local_users_passwords_dir: "{{luxnix_dest}}/secrets/user-passwords/{{inventory_hostname}}"
admin_password_file: "{{local_users_passwords_dir}}/admin_raw"
admin_password_file_source: "{{luxnix_dev_repo}}/secrets/user-passwords/{{inventory_hostname}}/admin_raw"