- name: Generate user passwords
  hosts: config_host
  gather_facts: false
  vars:
    default_users:
      - root
      - admin
    optional_users: []
  tasks:
    - name: Generate passwords for default and optional users
      connection: local
      custom_password_generator:
        user_list: "{{ default_users + optional_users }}"
        hostname: "{{ inventory_hostname }}"
