- name: Delete the luxnix production directory
  hosts: managed
  become: true
  become_user: "{{ ansible_become_user }}"
  vars:
    ansible_python_interpreter: "/run/current-system/sw/bin/python"
  tasks:
    - name: Delete the luxnix production directory
      ansible.builtin.file: # filepath = "{{ luxnix_dest }}"
        path: "{{ luxnix_dest }}"
        state: absent
