- name: Ensure luxnix-test-target contains an up-to-date Git repo
  hosts: test_group
  become: true
  become_user: "{{ ansible_become_user }}"
  tasks:
    - name: Clone or update the wg-lux/luxnix-refactor repository
      ansible.builtin.git:
        repo: "{{ luxnix_repo }}"
        dest: "{{ luxnix_dest }}"
        version: "{{ luxnix_branch }}"
        update: true
        force: true
      register: git_update
      notify: Allow direnv

  handlers:
    - name: Allow direnv
      ansible.builtin.command:
        cmd: "direnv allow {{ destination_dir }}/.envrc"
      changed_when: false
      when: git_update.changed
