- name: Ensure luxnix-test-target contains an up-to-date Git repo
  hosts: test_group
  become: true
  become_user: admin
  vars:
    luxnix_repo: "https://github.com/wg-lux/luxnix-refactor.git"
    luxnix_dest: "/home/admin/luxnix-test-target"
  tasks:
    - name: Ensure parent directories exist
      ansible.builtin.file:
        path: "{{ local_users_passwords_dir }}"
        state: directory

    - name: Clone or update the wg-lux/luxnix-refactor repository
      ansible.builtin.git:
        repo: "{{ luxnix_repo }}"
        dest: "{{ luxnix_dest }}"
        version: "dev"
        update: true
        force: true
      register: git_update

    - name: Ensure direnv allow has been run
      ansible.builtin.command:
        cmd: direnv status
      register: direnv_status
      failed_when: direnv_status.rc not in [0, 1]

    - name: Run direnv allow if required
      ansible.builtin.shell:
        cmd: direnv allow
      when: direnv_status.rc == 1

    - name: Transfer admin password file from source to target machine
      ansible.builtin.copy:
        src: "{{ admin_password_file_source }}"
        dest: "{{ admin_password_file }}"
        mode: 0600

    - name: Read admin password from file
      ansible.builtin.slurp:
        src: "{{ admin_password_file }}"
      register: admin_password_file

    - name: Set admin password fact
      set_fact:
        admin_password: "{{ admin_password_file.content | b64decode | string }}"

    - name: Run nh os switch if git repo was updated
      ansible.builtin.expect:
        command: nh os switch .
        responses:
          "Password:": "{{ admin_password }}"
      args:
        chdir: "{{ luxnix_dest }}"
      when: git_update.changed
