- name: Update Nix
  hosts: managed
  become: true
  become_user: "{{ ansible_become_user }}"
  tasks:
    - name: Clone or update the wg-lux/luxnix-refactor repository
      ansible.builtin.git:
        repo: "{{ luxnix_repo }}"
        dest: "{{ luxnix_dest }}"
        version: "{{ luxnix_branch }}"
        update: true
        force: false
      register: git_update
      # notify:
      #   - Allow direnv
      #   - Build devenv

    - name: Read admin password
      ansible.builtin.slurp:
        src: "{{ admin_password_file }}"
      register: user_password
      no_log: true

    - name: Run nho
      ansible.builtin.expect:
        command: "nh os switch"
        timeout: 900 # 15 Minutes
        responses:
          "(?i)\\[sudo\\]\\s*passwort\\s*für\\s*admin:": "{{ ansible_sudo_pass }}"
      become: true
      become_user: admin
      vars:
        ansible_sudo_pass: "{{ user_password.content | b64decode }}"
      async: 900 # 15 minutes
      poll: 5
      when: git_update.changed

    - name: Run nhh
      ansible.builtin.expect:
        command: "nh home switch"
        timeout: 900 # 15 Minutes
        responses:
          "(?i)\\[sudo\\]\\s*passwort\\s*für\\s*admin:": "{{ ansible_sudo_pass }}"
      become: true
      become_user: admin
      vars:
        ansible_sudo_pass: "{{ user_password.content | b64decode }}"
      async: 900 # 15 minutes
      poll: 5
      when: git_update.changed
